// src/app/data.rs

#[derive(Clone)]
pub struct Day {
    pub id: usize,
    pub title: &'static str,
    pub subtitle: &'static str,
    pub learn: &'static str,
    pub practice: &'static str,
    pub win: &'static str,
}

pub const DAYS: [Day; 12] = [
    Day {
        id: 1,
        title: "Patterns & Change",
        subtitle: "What comes next?",
        learn: "Math is like being a pattern detective. We look for what changes and what stays the same.",
        practice: "Do a few quick 'what comes next?' pattern puzzles.",
        win: "Tell someone how you spotted the pattern in one sentence.",
    },
    Day {
        id: 2,
        title: "Find the Missing Number",
        subtitle: "Balance the puzzle",
        learn: "Sometimes a number is hiding. We can figure it out by keeping both sides fair.",
        practice: "Solve missing-number puzzles like: 3 + __ = 7 or __ - 2 = 5.",
        win: "Make up your own missing-number puzzle for a parent or friend.",
    },
    Day {
        id: 3,
        title: "Shapes Around Us",
        subtitle: "Sides, corners, space",
        learn: "Shapes are everywhere! We notice sides, corners, and how shapes fit together.",
        practice: "Name shapes and count sides/corners. Try a perimeter or area puzzle if you’re ready.",
        win: "Find 3 shapes in your room and name them.",
    },
    Day {
        id: 4,
        title: "Angles & Turns",
        subtitle: "Spinning and tilting",
        learn: "Angles are turns. A little turn, a big turn, or a straight line — it’s all angles!",
        practice: "Compare turns (small/medium/large). Try a few angle or direction questions.",
        win: "Show a right angle using your arms (an L shape).",
    },
    Day {
        id: 5,
        title: "Making Sense of Numbers",
        subtitle: "Groups & averages",
        learn: "When we have a bunch of numbers, we can summarize them to understand the whole group.",
        practice: "Try mean/median/mode (or just 'most common' and 'middle' for younger grades).",
        win: "Explain which summary feels most fair for your answers.",
    },
    Day {
        id: 6,
        title: "Arrows & Grids",
        subtitle: "Moving and stretching",
        learn: "We can use arrows and grids to describe movement: left/right, up/down, bigger/smaller.",
        practice: "Do a few coordinate or 'move on the grid' puzzles. Try a simple table/grid rule.",
        win: "Give a robot directions to move on a grid (like 2 steps right, 1 step up).",
    },
    Day {
        id: 7,
        title: "What Might Happen?",
        subtitle: "Chances & guesses",
        learn: "Probability is a fancy word for 'chance' — how likely something is to happen.",
        practice: "Answer coin/dice/spinner questions like 'more likely' or 'less likely'.",
        win: "Name one real-life situation where you make a good guess using chance.",
    },
    Day {
        id: 8,
        title: "Number Secrets",
        subtitle: "Special numbers",
        learn: "Some numbers have special rules and patterns. We can test numbers and find secrets!",
        practice: "Try even/odd, skip counting, and prime/not-prime (for older grades).",
        win: "Pick a number and say one cool fact about it (even, odd, multiple, etc.).",
    },
    Day {
        id: 9,
        title: "Counting Smart",
        subtitle: "Rules & choices",
        learn: "Sometimes counting one-by-one is too slow. We learn smart ways to count choices.",
        practice: "Try counting paths, combinations of outfits/snacks, or subsets (for older grades).",
        win: "Tell how you counted without listing everything one at a time.",
    },
    Day {
        id: 10,
        title: "How Things Change",
        subtitle: "Faster, slower, steady",
        learn: "Some things change over time: speed, growth, temperature, points in a game.",
        practice: "Do a few 'rate' problems like 'each day adds 2' or 'each minute loses 1'.",
        win: "Describe something that changes in your life and how it changes.",
    },
    Day {
        id: 11,
        title: "How We Know",
        subtitle: "True or not?",
        learn: "Logic is how we know something is true. We use rules like 'if this, then that'.",
        practice: "Try true/false reasoning and simple 'if-then' puzzles.",
        win: "Explain why an answer is true using the word 'because'.",
    },
    Day {
        id: 12,
        title: "Choosing Wisely",
        subtitle: "Best moves",
        learn: "Game thinking is about choosing good moves — especially when someone else is choosing too.",
        practice: "Try a simple strategy puzzle: pick the best move or best choice.",
        win: "Teach a strategy tip you learned (like 'look ahead one step').",
    },
];
